import { ClerkProvider } from "@clerk/nextjs";
import { AuthControls } from "@/features/auth/auth-controls";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <ClerkProvider>
          <header className="flex items-center justify-between gap-4 px-6 py-4">
            <span className="text-sm font-semibold tracking-tight">
              LLM Arena
            </span>
            <AuthControls />
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
